package com.bsworld.springboot.start.dao.mapper;

import com.bsworld.springboot.start.dao.entity.TRateTransform;
import com.bsworld.springboot.start.dao.entity.TRateTransformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRateTransformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int countByExample(TRateTransformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int deleteByExample(TRateTransformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int insert(TRateTransform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int insertSelective(TRateTransform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    List<TRateTransform> selectByExample(TRateTransformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    TRateTransform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") TRateTransform record, @Param("example") TRateTransformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int updateByExample(@Param("record") TRateTransform record, @Param("example") TRateTransformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int updateByPrimaryKeySelective(TRateTransform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    int updateByPrimaryKey(TRateTransform record);
}