/*
package com.bsworld.springboot.start.dao.mapper;

import com.bsworld.springboot.start.dao.entity.User;
import com.bsworld.springboot.start.dao.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int countByExample(UserExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int deleteByExample(UserExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int deleteByPrimaryKey(Long id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int insert(User record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int insertSelective(User record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    List<User> selectByExample(UserExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    User selectByPrimaryKey(Long id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int updateByPrimaryKeySelective(User record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 24 18:38:14 CST 2018
     *//*

    int updateByPrimaryKey(User record);
}*/
