package com.bsworld.springboot.basic;

import java.util.Date;

public class TTransferOrder {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.ID
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.MER_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String merNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.PARENT_MER_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String parentMerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.IS_BATCH
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Short isBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.FLOW_LVL_CURRENT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String flowLvlCurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.MER_TRAN_SEQ
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String merTranSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.TRANSFER_TRAN_SEQ
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String transferTranSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.ACCOUNT_NUMBER
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.ACCOUNT_HOLDER_NAME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String accountHolderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BENEFI_ADDRESS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String benefiAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BANK_NAME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BANK_ADDRESS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String bankAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.SWIFT_BIC
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String swiftBic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BANK_CODE_TYPE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String bankCodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BANK_CODE_VALUE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String bankCodeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.ACC_CURRENCY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String accCurrencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.COUNTRY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BENEFI_CITY
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String benefiCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BENEFI_ENTITY_TYPE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String benefiEntityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BENEFI_DOB
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String benefiDob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.PAY_CURRENCY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String payCurrencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.AMOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.TOTAL_AMOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Long totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.PRO_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.CHL_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String chlNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.MER_ACCOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String merAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.UNPAY_ACCOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String unpayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.DESCRIPTION
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.TRAN_FLAG
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Short tranFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BATCH_PATH
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String batchPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.BATCH_PATH_FINAL
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String batchPathFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.PAY_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.PAY_USER
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private String payUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.CREATE_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.TRAN_STATUS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Short tranStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.UPDATE_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_order.DELETE_FLAG
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    private Short deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.ID
     *
     * @return the value of t_transfer_order.ID
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.ID
     *
     * @param id the value for t_transfer_order.ID
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.MER_NO
     *
     * @return the value of t_transfer_order.MER_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getMerNo() {
        return merNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.MER_NO
     *
     * @param merNo the value for t_transfer_order.MER_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setMerNo(String merNo) {
        this.merNo = merNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.PARENT_MER_NO
     *
     * @return the value of t_transfer_order.PARENT_MER_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getParentMerNo() {
        return parentMerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.PARENT_MER_NO
     *
     * @param parentMerNo the value for t_transfer_order.PARENT_MER_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setParentMerNo(String parentMerNo) {
        this.parentMerNo = parentMerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.IS_BATCH
     *
     * @return the value of t_transfer_order.IS_BATCH
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Short getIsBatch() {
        return isBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.IS_BATCH
     *
     * @param isBatch the value for t_transfer_order.IS_BATCH
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setIsBatch(Short isBatch) {
        this.isBatch = isBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.FLOW_LVL_CURRENT
     *
     * @return the value of t_transfer_order.FLOW_LVL_CURRENT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getFlowLvlCurrent() {
        return flowLvlCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.FLOW_LVL_CURRENT
     *
     * @param flowLvlCurrent the value for t_transfer_order.FLOW_LVL_CURRENT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setFlowLvlCurrent(String flowLvlCurrent) {
        this.flowLvlCurrent = flowLvlCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.MER_TRAN_SEQ
     *
     * @return the value of t_transfer_order.MER_TRAN_SEQ
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getMerTranSeq() {
        return merTranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.MER_TRAN_SEQ
     *
     * @param merTranSeq the value for t_transfer_order.MER_TRAN_SEQ
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setMerTranSeq(String merTranSeq) {
        this.merTranSeq = merTranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.TRANSFER_TRAN_SEQ
     *
     * @return the value of t_transfer_order.TRANSFER_TRAN_SEQ
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getTransferTranSeq() {
        return transferTranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.TRANSFER_TRAN_SEQ
     *
     * @param transferTranSeq the value for t_transfer_order.TRANSFER_TRAN_SEQ
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setTransferTranSeq(String transferTranSeq) {
        this.transferTranSeq = transferTranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.ACCOUNT_NUMBER
     *
     * @return the value of t_transfer_order.ACCOUNT_NUMBER
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.ACCOUNT_NUMBER
     *
     * @param accountNumber the value for t_transfer_order.ACCOUNT_NUMBER
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.ACCOUNT_HOLDER_NAME
     *
     * @return the value of t_transfer_order.ACCOUNT_HOLDER_NAME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getAccountHolderName() {
        return accountHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.ACCOUNT_HOLDER_NAME
     *
     * @param accountHolderName the value for t_transfer_order.ACCOUNT_HOLDER_NAME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setAccountHolderName(String accountHolderName) {
        this.accountHolderName = accountHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BENEFI_ADDRESS
     *
     * @return the value of t_transfer_order.BENEFI_ADDRESS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBenefiAddress() {
        return benefiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BENEFI_ADDRESS
     *
     * @param benefiAddress the value for t_transfer_order.BENEFI_ADDRESS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBenefiAddress(String benefiAddress) {
        this.benefiAddress = benefiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BANK_NAME
     *
     * @return the value of t_transfer_order.BANK_NAME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BANK_NAME
     *
     * @param bankName the value for t_transfer_order.BANK_NAME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BANK_ADDRESS
     *
     * @return the value of t_transfer_order.BANK_ADDRESS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BANK_ADDRESS
     *
     * @param bankAddress the value for t_transfer_order.BANK_ADDRESS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.SWIFT_BIC
     *
     * @return the value of t_transfer_order.SWIFT_BIC
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getSwiftBic() {
        return swiftBic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.SWIFT_BIC
     *
     * @param swiftBic the value for t_transfer_order.SWIFT_BIC
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setSwiftBic(String swiftBic) {
        this.swiftBic = swiftBic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BANK_CODE_TYPE
     *
     * @return the value of t_transfer_order.BANK_CODE_TYPE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBankCodeType() {
        return bankCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BANK_CODE_TYPE
     *
     * @param bankCodeType the value for t_transfer_order.BANK_CODE_TYPE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBankCodeType(String bankCodeType) {
        this.bankCodeType = bankCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BANK_CODE_VALUE
     *
     * @return the value of t_transfer_order.BANK_CODE_VALUE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBankCodeValue() {
        return bankCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BANK_CODE_VALUE
     *
     * @param bankCodeValue the value for t_transfer_order.BANK_CODE_VALUE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBankCodeValue(String bankCodeValue) {
        this.bankCodeValue = bankCodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.ACC_CURRENCY_CODE
     *
     * @return the value of t_transfer_order.ACC_CURRENCY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getAccCurrencyCode() {
        return accCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.ACC_CURRENCY_CODE
     *
     * @param accCurrencyCode the value for t_transfer_order.ACC_CURRENCY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setAccCurrencyCode(String accCurrencyCode) {
        this.accCurrencyCode = accCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.COUNTRY_CODE
     *
     * @return the value of t_transfer_order.COUNTRY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.COUNTRY_CODE
     *
     * @param countryCode the value for t_transfer_order.COUNTRY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BENEFI_CITY
     *
     * @return the value of t_transfer_order.BENEFI_CITY
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBenefiCity() {
        return benefiCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BENEFI_CITY
     *
     * @param benefiCity the value for t_transfer_order.BENEFI_CITY
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBenefiCity(String benefiCity) {
        this.benefiCity = benefiCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BENEFI_ENTITY_TYPE
     *
     * @return the value of t_transfer_order.BENEFI_ENTITY_TYPE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBenefiEntityType() {
        return benefiEntityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BENEFI_ENTITY_TYPE
     *
     * @param benefiEntityType the value for t_transfer_order.BENEFI_ENTITY_TYPE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBenefiEntityType(String benefiEntityType) {
        this.benefiEntityType = benefiEntityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BENEFI_DOB
     *
     * @return the value of t_transfer_order.BENEFI_DOB
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBenefiDob() {
        return benefiDob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BENEFI_DOB
     *
     * @param benefiDob the value for t_transfer_order.BENEFI_DOB
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBenefiDob(String benefiDob) {
        this.benefiDob = benefiDob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.PAY_CURRENCY_CODE
     *
     * @return the value of t_transfer_order.PAY_CURRENCY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getPayCurrencyCode() {
        return payCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.PAY_CURRENCY_CODE
     *
     * @param payCurrencyCode the value for t_transfer_order.PAY_CURRENCY_CODE
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setPayCurrencyCode(String payCurrencyCode) {
        this.payCurrencyCode = payCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.AMOUNT
     *
     * @return the value of t_transfer_order.AMOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.AMOUNT
     *
     * @param amount the value for t_transfer_order.AMOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.TOTAL_AMOUNT
     *
     * @return the value of t_transfer_order.TOTAL_AMOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.TOTAL_AMOUNT
     *
     * @param totalAmount the value for t_transfer_order.TOTAL_AMOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.PRO_NO
     *
     * @return the value of t_transfer_order.PRO_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.PRO_NO
     *
     * @param proNo the value for t_transfer_order.PRO_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setProNo(String proNo) {
        this.proNo = proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.CHL_NO
     *
     * @return the value of t_transfer_order.CHL_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getChlNo() {
        return chlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.CHL_NO
     *
     * @param chlNo the value for t_transfer_order.CHL_NO
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setChlNo(String chlNo) {
        this.chlNo = chlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.MER_ACCOUNT
     *
     * @return the value of t_transfer_order.MER_ACCOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getMerAccount() {
        return merAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.MER_ACCOUNT
     *
     * @param merAccount the value for t_transfer_order.MER_ACCOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setMerAccount(String merAccount) {
        this.merAccount = merAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.UNPAY_ACCOUNT
     *
     * @return the value of t_transfer_order.UNPAY_ACCOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getUnpayAccount() {
        return unpayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.UNPAY_ACCOUNT
     *
     * @param unpayAccount the value for t_transfer_order.UNPAY_ACCOUNT
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setUnpayAccount(String unpayAccount) {
        this.unpayAccount = unpayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.DESCRIPTION
     *
     * @return the value of t_transfer_order.DESCRIPTION
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.DESCRIPTION
     *
     * @param description the value for t_transfer_order.DESCRIPTION
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.TRAN_FLAG
     *
     * @return the value of t_transfer_order.TRAN_FLAG
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Short getTranFlag() {
        return tranFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.TRAN_FLAG
     *
     * @param tranFlag the value for t_transfer_order.TRAN_FLAG
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setTranFlag(Short tranFlag) {
        this.tranFlag = tranFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BATCH_PATH
     *
     * @return the value of t_transfer_order.BATCH_PATH
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBatchPath() {
        return batchPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BATCH_PATH
     *
     * @param batchPath the value for t_transfer_order.BATCH_PATH
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBatchPath(String batchPath) {
        this.batchPath = batchPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.BATCH_PATH_FINAL
     *
     * @return the value of t_transfer_order.BATCH_PATH_FINAL
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getBatchPathFinal() {
        return batchPathFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.BATCH_PATH_FINAL
     *
     * @param batchPathFinal the value for t_transfer_order.BATCH_PATH_FINAL
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setBatchPathFinal(String batchPathFinal) {
        this.batchPathFinal = batchPathFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.PAY_TIME
     *
     * @return the value of t_transfer_order.PAY_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.PAY_TIME
     *
     * @param payTime the value for t_transfer_order.PAY_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.PAY_USER
     *
     * @return the value of t_transfer_order.PAY_USER
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public String getPayUser() {
        return payUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.PAY_USER
     *
     * @param payUser the value for t_transfer_order.PAY_USER
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setPayUser(String payUser) {
        this.payUser = payUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.CREATE_TIME
     *
     * @return the value of t_transfer_order.CREATE_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.CREATE_TIME
     *
     * @param createTime the value for t_transfer_order.CREATE_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.TRAN_STATUS
     *
     * @return the value of t_transfer_order.TRAN_STATUS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Short getTranStatus() {
        return tranStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.TRAN_STATUS
     *
     * @param tranStatus the value for t_transfer_order.TRAN_STATUS
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setTranStatus(Short tranStatus) {
        this.tranStatus = tranStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.UPDATE_TIME
     *
     * @return the value of t_transfer_order.UPDATE_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.UPDATE_TIME
     *
     * @param updateTime the value for t_transfer_order.UPDATE_TIME
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_order.DELETE_FLAG
     *
     * @return the value of t_transfer_order.DELETE_FLAG
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_order.DELETE_FLAG
     *
     * @param deleteFlag the value for t_transfer_order.DELETE_FLAG
     *
     * @mbggenerated Fri Aug 17 10:23:52 CST 2018
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}