package com.bsworld.springboot.basic;

/**
 * program: Final
 * author: bsworld.xie
 * create: 2019-07-17 19:56
 * description:
 */
public class UserBuyGoodsInfoPo {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.novel_id
     *
     * @mbg.generated
     */
    private Long novelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.uid
     *
     * @return the value of user_buy_goods_info.uid
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.uid
     *
     * @param uid the value for user_buy_goods_info.uid
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.novel_id
     *
     * @return the value of user_buy_goods_info.novel_id
     * @mbg.generated
     */
    public Long getNovelId() {
        return novelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.novel_id
     *
     * @param novelId the value for user_buy_goods_info.novel_id
     * @mbg.generated
     */
    public void setNovelId(Long novelId) {
        this.novelId = novelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.goods_id
     *
     * @return the value of user_buy_goods_info.goods_id
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.goods_id
     *
     * @param goodsId the value for user_buy_goods_info.goods_id
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.buy_count
     *
     * @mbg.generated
     */
    private Integer buyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_buy_goods_info.progress_map
     *
     * @mbg.generated
     */
    private String progressMap;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.create_time
     *
     * @return the value of user_buy_goods_info.create_time
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.create_time
     *
     * @param createTime the value for user_buy_goods_info.create_time
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.update_time
     *
     * @return the value of user_buy_goods_info.update_time
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.update_time
     *
     * @param updateTime the value for user_buy_goods_info.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.buy_count
     *
     * @return the value of user_buy_goods_info.buy_count
     * @mbg.generated
     */
    public Integer getBuyCount() {
        return buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.buy_count
     *
     * @param buyCount the value for user_buy_goods_info.buy_count
     * @mbg.generated
     */
    public void setBuyCount(Integer buyCount) {
        this.buyCount = buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_buy_goods_info.progress_map
     *
     * @return the value of user_buy_goods_info.progress_map
     * @mbg.generated
     */
    public String getProgressMap() {
        return progressMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_buy_goods_info.progress_map
     *
     * @param progressMap the value for user_buy_goods_info.progress_map
     * @mbg.generated
     */
    public void setProgressMap(String progressMap) {
        this.progressMap = progressMap == null ? null : progressMap.trim();
    }
}
