package com.bsworld.springboot.start.dao.entity;
public class TPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permissionname
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    private String permissionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.role_id
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permissionname
     *
     * @return the value of t_permission.permissionname
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permissionname
     *
     * @param permissionname the value for t_permission.permissionname
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.role_id
     *
     * @return the value of t_permission.role_id
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.role_id
     *
     * @param roleId the value for t_permission.role_id
     *
     * @mbggenerated Mon Jul 30 17:55:08 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}