package com.bsworld.springboot.start.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TRateTransformExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public TRateTransformExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChannelNoIsNull() {
            addCriterion("CHANNEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andChannelNoIsNotNull() {
            addCriterion("CHANNEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNoEqualTo(String value) {
            addCriterion("CHANNEL_NO =", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotEqualTo(String value) {
            addCriterion("CHANNEL_NO <>", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoGreaterThan(String value) {
            addCriterion("CHANNEL_NO >", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_NO >=", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoLessThan(String value) {
            addCriterion("CHANNEL_NO <", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_NO <=", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoLike(String value) {
            addCriterion("CHANNEL_NO like", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotLike(String value) {
            addCriterion("CHANNEL_NO not like", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoIn(List<String> values) {
            addCriterion("CHANNEL_NO in", values, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotIn(List<String> values) {
            addCriterion("CHANNEL_NO not in", values, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoBetween(String value1, String value2) {
            addCriterion("CHANNEL_NO between", value1, value2, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_NO not between", value1, value2, "channelNo");
            return (Criteria) this;
        }

        public Criteria andFromCurIsNull() {
            addCriterion("FROM_CUR is null");
            return (Criteria) this;
        }

        public Criteria andFromCurIsNotNull() {
            addCriterion("FROM_CUR is not null");
            return (Criteria) this;
        }

        public Criteria andFromCurEqualTo(String value) {
            addCriterion("FROM_CUR =", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurNotEqualTo(String value) {
            addCriterion("FROM_CUR <>", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurGreaterThan(String value) {
            addCriterion("FROM_CUR >", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurGreaterThanOrEqualTo(String value) {
            addCriterion("FROM_CUR >=", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurLessThan(String value) {
            addCriterion("FROM_CUR <", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurLessThanOrEqualTo(String value) {
            addCriterion("FROM_CUR <=", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurLike(String value) {
            addCriterion("FROM_CUR like", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurNotLike(String value) {
            addCriterion("FROM_CUR not like", value, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurIn(List<String> values) {
            addCriterion("FROM_CUR in", values, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurNotIn(List<String> values) {
            addCriterion("FROM_CUR not in", values, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurBetween(String value1, String value2) {
            addCriterion("FROM_CUR between", value1, value2, "fromCur");
            return (Criteria) this;
        }

        public Criteria andFromCurNotBetween(String value1, String value2) {
            addCriterion("FROM_CUR not between", value1, value2, "fromCur");
            return (Criteria) this;
        }

        public Criteria andToCurIsNull() {
            addCriterion("TO_CUR is null");
            return (Criteria) this;
        }

        public Criteria andToCurIsNotNull() {
            addCriterion("TO_CUR is not null");
            return (Criteria) this;
        }

        public Criteria andToCurEqualTo(String value) {
            addCriterion("TO_CUR =", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurNotEqualTo(String value) {
            addCriterion("TO_CUR <>", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurGreaterThan(String value) {
            addCriterion("TO_CUR >", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurGreaterThanOrEqualTo(String value) {
            addCriterion("TO_CUR >=", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurLessThan(String value) {
            addCriterion("TO_CUR <", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurLessThanOrEqualTo(String value) {
            addCriterion("TO_CUR <=", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurLike(String value) {
            addCriterion("TO_CUR like", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurNotLike(String value) {
            addCriterion("TO_CUR not like", value, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurIn(List<String> values) {
            addCriterion("TO_CUR in", values, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurNotIn(List<String> values) {
            addCriterion("TO_CUR not in", values, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurBetween(String value1, String value2) {
            addCriterion("TO_CUR between", value1, value2, "toCur");
            return (Criteria) this;
        }

        public Criteria andToCurNotBetween(String value1, String value2) {
            addCriterion("TO_CUR not between", value1, value2, "toCur");
            return (Criteria) this;
        }

        public Criteria andChlRateIsNull() {
            addCriterion("CHL_RATE is null");
            return (Criteria) this;
        }

        public Criteria andChlRateIsNotNull() {
            addCriterion("CHL_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andChlRateEqualTo(BigDecimal value) {
            addCriterion("CHL_RATE =", value, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateNotEqualTo(BigDecimal value) {
            addCriterion("CHL_RATE <>", value, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateGreaterThan(BigDecimal value) {
            addCriterion("CHL_RATE >", value, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CHL_RATE >=", value, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateLessThan(BigDecimal value) {
            addCriterion("CHL_RATE <", value, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CHL_RATE <=", value, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateIn(List<BigDecimal> values) {
            addCriterion("CHL_RATE in", values, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateNotIn(List<BigDecimal> values) {
            addCriterion("CHL_RATE not in", values, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHL_RATE between", value1, value2, "chlRate");
            return (Criteria) this;
        }

        public Criteria andChlRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHL_RATE not between", value1, value2, "chlRate");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairIsNull() {
            addCriterion("CURRENCY_PAIR is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairIsNotNull() {
            addCriterion("CURRENCY_PAIR is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairEqualTo(String value) {
            addCriterion("CURRENCY_PAIR =", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairNotEqualTo(String value) {
            addCriterion("CURRENCY_PAIR <>", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairGreaterThan(String value) {
            addCriterion("CURRENCY_PAIR >", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY_PAIR >=", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairLessThan(String value) {
            addCriterion("CURRENCY_PAIR <", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY_PAIR <=", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairLike(String value) {
            addCriterion("CURRENCY_PAIR like", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairNotLike(String value) {
            addCriterion("CURRENCY_PAIR not like", value, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairIn(List<String> values) {
            addCriterion("CURRENCY_PAIR in", values, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairNotIn(List<String> values) {
            addCriterion("CURRENCY_PAIR not in", values, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairBetween(String value1, String value2) {
            addCriterion("CURRENCY_PAIR between", value1, value2, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andCurrencyPairNotBetween(String value1, String value2) {
            addCriterion("CURRENCY_PAIR not between", value1, value2, "currencyPair");
            return (Criteria) this;
        }

        public Criteria andMerRateIsNull() {
            addCriterion("MER_RATE is null");
            return (Criteria) this;
        }

        public Criteria andMerRateIsNotNull() {
            addCriterion("MER_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andMerRateEqualTo(BigDecimal value) {
            addCriterion("MER_RATE =", value, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateNotEqualTo(BigDecimal value) {
            addCriterion("MER_RATE <>", value, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateGreaterThan(BigDecimal value) {
            addCriterion("MER_RATE >", value, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MER_RATE >=", value, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateLessThan(BigDecimal value) {
            addCriterion("MER_RATE <", value, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MER_RATE <=", value, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateIn(List<BigDecimal> values) {
            addCriterion("MER_RATE in", values, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateNotIn(List<BigDecimal> values) {
            addCriterion("MER_RATE not in", values, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MER_RATE between", value1, value2, "merRate");
            return (Criteria) this;
        }

        public Criteria andMerRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MER_RATE not between", value1, value2, "merRate");
            return (Criteria) this;
        }

        public Criteria andInTypeIsNull() {
            addCriterion("IN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andInTypeIsNotNull() {
            addCriterion("IN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andInTypeEqualTo(Short value) {
            addCriterion("IN_TYPE =", value, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeNotEqualTo(Short value) {
            addCriterion("IN_TYPE <>", value, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeGreaterThan(Short value) {
            addCriterion("IN_TYPE >", value, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("IN_TYPE >=", value, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeLessThan(Short value) {
            addCriterion("IN_TYPE <", value, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeLessThanOrEqualTo(Short value) {
            addCriterion("IN_TYPE <=", value, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeIn(List<Short> values) {
            addCriterion("IN_TYPE in", values, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeNotIn(List<Short> values) {
            addCriterion("IN_TYPE not in", values, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeBetween(Short value1, Short value2) {
            addCriterion("IN_TYPE between", value1, value2, "inType");
            return (Criteria) this;
        }

        public Criteria andInTypeNotBetween(Short value1, Short value2) {
            addCriterion("IN_TYPE not between", value1, value2, "inType");
            return (Criteria) this;
        }

        public Criteria andInPricePerIsNull() {
            addCriterion("IN_PRICE_PER is null");
            return (Criteria) this;
        }

        public Criteria andInPricePerIsNotNull() {
            addCriterion("IN_PRICE_PER is not null");
            return (Criteria) this;
        }

        public Criteria andInPricePerEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_PER =", value, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerNotEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_PER <>", value, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerGreaterThan(BigDecimal value) {
            addCriterion("IN_PRICE_PER >", value, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_PER >=", value, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerLessThan(BigDecimal value) {
            addCriterion("IN_PRICE_PER <", value, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_PER <=", value, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerIn(List<BigDecimal> values) {
            addCriterion("IN_PRICE_PER in", values, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerNotIn(List<BigDecimal> values) {
            addCriterion("IN_PRICE_PER not in", values, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IN_PRICE_PER between", value1, value2, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPricePerNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IN_PRICE_PER not between", value1, value2, "inPricePer");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioIsNull() {
            addCriterion("IN_PRICE_AGIO is null");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioIsNotNull() {
            addCriterion("IN_PRICE_AGIO is not null");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_AGIO =", value, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioNotEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_AGIO <>", value, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioGreaterThan(BigDecimal value) {
            addCriterion("IN_PRICE_AGIO >", value, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_AGIO >=", value, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioLessThan(BigDecimal value) {
            addCriterion("IN_PRICE_AGIO <", value, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IN_PRICE_AGIO <=", value, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioIn(List<BigDecimal> values) {
            addCriterion("IN_PRICE_AGIO in", values, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioNotIn(List<BigDecimal> values) {
            addCriterion("IN_PRICE_AGIO not in", values, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IN_PRICE_AGIO between", value1, value2, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInPriceAgioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IN_PRICE_AGIO not between", value1, value2, "inPriceAgio");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagIsNull() {
            addCriterion("INVALID_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagIsNotNull() {
            addCriterion("INVALID_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagEqualTo(Short value) {
            addCriterion("INVALID_FLAG =", value, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagNotEqualTo(Short value) {
            addCriterion("INVALID_FLAG <>", value, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagGreaterThan(Short value) {
            addCriterion("INVALID_FLAG >", value, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("INVALID_FLAG >=", value, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagLessThan(Short value) {
            addCriterion("INVALID_FLAG <", value, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagLessThanOrEqualTo(Short value) {
            addCriterion("INVALID_FLAG <=", value, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagIn(List<Short> values) {
            addCriterion("INVALID_FLAG in", values, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagNotIn(List<Short> values) {
            addCriterion("INVALID_FLAG not in", values, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagBetween(Short value1, Short value2) {
            addCriterion("INVALID_FLAG between", value1, value2, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andInvalidFlagNotBetween(Short value1, Short value2) {
            addCriterion("INVALID_FLAG not between", value1, value2, "invalidFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagIsNull() {
            addCriterion("ON_OFF_LINE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagIsNotNull() {
            addCriterion("ON_OFF_LINE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagEqualTo(Short value) {
            addCriterion("ON_OFF_LINE_FLAG =", value, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagNotEqualTo(Short value) {
            addCriterion("ON_OFF_LINE_FLAG <>", value, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagGreaterThan(Short value) {
            addCriterion("ON_OFF_LINE_FLAG >", value, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("ON_OFF_LINE_FLAG >=", value, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagLessThan(Short value) {
            addCriterion("ON_OFF_LINE_FLAG <", value, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagLessThanOrEqualTo(Short value) {
            addCriterion("ON_OFF_LINE_FLAG <=", value, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagIn(List<Short> values) {
            addCriterion("ON_OFF_LINE_FLAG in", values, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagNotIn(List<Short> values) {
            addCriterion("ON_OFF_LINE_FLAG not in", values, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagBetween(Short value1, Short value2) {
            addCriterion("ON_OFF_LINE_FLAG between", value1, value2, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andOnOffLineFlagNotBetween(Short value1, Short value2) {
            addCriterion("ON_OFF_LINE_FLAG not between", value1, value2, "onOffLineFlag");
            return (Criteria) this;
        }

        public Criteria andPushDateIsNull() {
            addCriterion("PUSH_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPushDateIsNotNull() {
            addCriterion("PUSH_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPushDateEqualTo(String value) {
            addCriterion("PUSH_DATE =", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateNotEqualTo(String value) {
            addCriterion("PUSH_DATE <>", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateGreaterThan(String value) {
            addCriterion("PUSH_DATE >", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateGreaterThanOrEqualTo(String value) {
            addCriterion("PUSH_DATE >=", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateLessThan(String value) {
            addCriterion("PUSH_DATE <", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateLessThanOrEqualTo(String value) {
            addCriterion("PUSH_DATE <=", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateLike(String value) {
            addCriterion("PUSH_DATE like", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateNotLike(String value) {
            addCriterion("PUSH_DATE not like", value, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateIn(List<String> values) {
            addCriterion("PUSH_DATE in", values, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateNotIn(List<String> values) {
            addCriterion("PUSH_DATE not in", values, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateBetween(String value1, String value2) {
            addCriterion("PUSH_DATE between", value1, value2, "pushDate");
            return (Criteria) this;
        }

        public Criteria andPushDateNotBetween(String value1, String value2) {
            addCriterion("PUSH_DATE not between", value1, value2, "pushDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateIsNull() {
            addCriterion("TRANSFORM_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTransformDateIsNotNull() {
            addCriterion("TRANSFORM_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTransformDateEqualTo(String value) {
            addCriterion("TRANSFORM_DATE =", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateNotEqualTo(String value) {
            addCriterion("TRANSFORM_DATE <>", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateGreaterThan(String value) {
            addCriterion("TRANSFORM_DATE >", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFORM_DATE >=", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateLessThan(String value) {
            addCriterion("TRANSFORM_DATE <", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateLessThanOrEqualTo(String value) {
            addCriterion("TRANSFORM_DATE <=", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateLike(String value) {
            addCriterion("TRANSFORM_DATE like", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateNotLike(String value) {
            addCriterion("TRANSFORM_DATE not like", value, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateIn(List<String> values) {
            addCriterion("TRANSFORM_DATE in", values, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateNotIn(List<String> values) {
            addCriterion("TRANSFORM_DATE not in", values, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateBetween(String value1, String value2) {
            addCriterion("TRANSFORM_DATE between", value1, value2, "transformDate");
            return (Criteria) this;
        }

        public Criteria andTransformDateNotBetween(String value1, String value2) {
            addCriterion("TRANSFORM_DATE not between", value1, value2, "transformDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rate_transform
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 14 17:40:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rate_transform
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}