package com.bsworld.springboot.start.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TRateTransform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.ID
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.CHANNEL_NO
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String channelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.FROM_CUR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String fromCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.TO_CUR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String toCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.CHL_RATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private BigDecimal chlRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.CURRENCY_PAIR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String currencyPair;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.MER_RATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private BigDecimal merRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.IN_TYPE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private Short inType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.IN_PRICE_PER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private BigDecimal inPricePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.IN_PRICE_AGIO
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private BigDecimal inPriceAgio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.INVALID_FLAG
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private Short invalidFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.ON_OFF_LINE_FLAG
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private Short onOffLineFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.PUSH_DATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String pushDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.TRANSFORM_DATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String transformDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.CREATE_TIME
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.MODIFY_TIME
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.CREATE_USER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rate_transform.UPDATE_USER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.ID
     *
     * @return the value of t_rate_transform.ID
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.ID
     *
     * @param id the value for t_rate_transform.ID
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.CHANNEL_NO
     *
     * @return the value of t_rate_transform.CHANNEL_NO
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.CHANNEL_NO
     *
     * @param channelNo the value for t_rate_transform.CHANNEL_NO
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setChannelNo(String channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.FROM_CUR
     *
     * @return the value of t_rate_transform.FROM_CUR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getFromCur() {
        return fromCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.FROM_CUR
     *
     * @param fromCur the value for t_rate_transform.FROM_CUR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setFromCur(String fromCur) {
        this.fromCur = fromCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.TO_CUR
     *
     * @return the value of t_rate_transform.TO_CUR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getToCur() {
        return toCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.TO_CUR
     *
     * @param toCur the value for t_rate_transform.TO_CUR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setToCur(String toCur) {
        this.toCur = toCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.CHL_RATE
     *
     * @return the value of t_rate_transform.CHL_RATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public BigDecimal getChlRate() {
        return chlRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.CHL_RATE
     *
     * @param chlRate the value for t_rate_transform.CHL_RATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setChlRate(BigDecimal chlRate) {
        this.chlRate = chlRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.CURRENCY_PAIR
     *
     * @return the value of t_rate_transform.CURRENCY_PAIR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getCurrencyPair() {
        return currencyPair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.CURRENCY_PAIR
     *
     * @param currencyPair the value for t_rate_transform.CURRENCY_PAIR
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setCurrencyPair(String currencyPair) {
        this.currencyPair = currencyPair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.MER_RATE
     *
     * @return the value of t_rate_transform.MER_RATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public BigDecimal getMerRate() {
        return merRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.MER_RATE
     *
     * @param merRate the value for t_rate_transform.MER_RATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setMerRate(BigDecimal merRate) {
        this.merRate = merRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.IN_TYPE
     *
     * @return the value of t_rate_transform.IN_TYPE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Short getInType() {
        return inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.IN_TYPE
     *
     * @param inType the value for t_rate_transform.IN_TYPE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setInType(Short inType) {
        this.inType = inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.IN_PRICE_PER
     *
     * @return the value of t_rate_transform.IN_PRICE_PER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public BigDecimal getInPricePer() {
        return inPricePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.IN_PRICE_PER
     *
     * @param inPricePer the value for t_rate_transform.IN_PRICE_PER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setInPricePer(BigDecimal inPricePer) {
        this.inPricePer = inPricePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.IN_PRICE_AGIO
     *
     * @return the value of t_rate_transform.IN_PRICE_AGIO
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public BigDecimal getInPriceAgio() {
        return inPriceAgio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.IN_PRICE_AGIO
     *
     * @param inPriceAgio the value for t_rate_transform.IN_PRICE_AGIO
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setInPriceAgio(BigDecimal inPriceAgio) {
        this.inPriceAgio = inPriceAgio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.INVALID_FLAG
     *
     * @return the value of t_rate_transform.INVALID_FLAG
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Short getInvalidFlag() {
        return invalidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.INVALID_FLAG
     *
     * @param invalidFlag the value for t_rate_transform.INVALID_FLAG
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setInvalidFlag(Short invalidFlag) {
        this.invalidFlag = invalidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.ON_OFF_LINE_FLAG
     *
     * @return the value of t_rate_transform.ON_OFF_LINE_FLAG
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Short getOnOffLineFlag() {
        return onOffLineFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.ON_OFF_LINE_FLAG
     *
     * @param onOffLineFlag the value for t_rate_transform.ON_OFF_LINE_FLAG
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setOnOffLineFlag(Short onOffLineFlag) {
        this.onOffLineFlag = onOffLineFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.PUSH_DATE
     *
     * @return the value of t_rate_transform.PUSH_DATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getPushDate() {
        return pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.PUSH_DATE
     *
     * @param pushDate the value for t_rate_transform.PUSH_DATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setPushDate(String pushDate) {
        this.pushDate = pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.TRANSFORM_DATE
     *
     * @return the value of t_rate_transform.TRANSFORM_DATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getTransformDate() {
        return transformDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.TRANSFORM_DATE
     *
     * @param transformDate the value for t_rate_transform.TRANSFORM_DATE
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setTransformDate(String transformDate) {
        this.transformDate = transformDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.CREATE_TIME
     *
     * @return the value of t_rate_transform.CREATE_TIME
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.CREATE_TIME
     *
     * @param createTime the value for t_rate_transform.CREATE_TIME
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.MODIFY_TIME
     *
     * @return the value of t_rate_transform.MODIFY_TIME
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.MODIFY_TIME
     *
     * @param modifyTime the value for t_rate_transform.MODIFY_TIME
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.CREATE_USER
     *
     * @return the value of t_rate_transform.CREATE_USER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.CREATE_USER
     *
     * @param createUser the value for t_rate_transform.CREATE_USER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rate_transform.UPDATE_USER
     *
     * @return the value of t_rate_transform.UPDATE_USER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rate_transform.UPDATE_USER
     *
     * @param updateUser the value for t_rate_transform.UPDATE_USER
     *
     * @mbggenerated Fri Sep 14 17:40:37 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}